### ISSUE TITLE
Stack?

### ISSUE THREAD

**Issue by aneesh-neelam** [aneesh-neelam/VITacademics-Worker#2]
So, which stack do you want to use? 

The options are: 
* Node.js/io.js (Same as the HTTP API Backend)
* Python 3 (no Python 2, not anymore please)
* Go (:-D)
* Java (If you want to tear your hair out)
* C++ (Might be fun :-P)

All of them have their pros and cons. But remember, we'll be running a single core, 512 MB RAM dyno for this, so decide accordingly. 

What we need: 
* Loads of IO (Network, Database etc. )
* Very little CPU (I've checked the backend's logs, it uses less than 10% of CPU on average)
* Good amount of memory (512 MB should do)

**Comment by karthikb351** [comment]
Before we start discussing stack, we need to spec out the system. Let's list them out.

- GCM dispatch
- iOS dispatch
- CRON?

**Comment by aneesh-neelam** [comment]
Let's discuss the spec on #3.

**Comment by kishore-narendran** [comment]
I think we should do Node only.

**Comment by aneesh-neelam** [comment]
OK. Node.js/io.js it is. Reopen if you change your mind.
